r"""
Module 3 -- the fold report as the paper consumes it (Member 2).

Separated from splits.py because the two answer different questions.
splits.py decides which wells go where and must stay readable as the
leakage control it is; this file only turns that decision into LaTeX.
Nothing here affects a fold, so a change to the table's appearance can
never change a result.

It lives under src/data rather than in src/eval/aggregate.py, where the
other .tex writers are, for two reasons: the fold report is Module 3's
output and src/eval is another member's ownership area, and src/data
already carries this pattern -- src/data/stats.py renders the paper's
dataset figures the same way.

One inconsistency is worth recording rather than quietly living with:
aggregate.py's tables use \hline while this one uses booktabs, which
report.tex's preamble loads and which the hand-written tables in the
paper already use. The five generated result tables will look different
from the other three until that is unified, which belongs on the eval
side.
"""

from __future__ import annotations

import pandas as pd


def fold_report_to_latex(
    report: pd.DataFrame,
    caption: str | None = None,
    label: str = "tab:folds",
) -> str:
    """
    Render fold_report() as the booktabs table the paper \\input{}s.

    Written here rather than hand-copied into report.tex because the team
    contract says no number in the paper is typed by hand: regenerate the
    file and the table updates with it. The column set is the one a reader
    needs to judge whether a fold can support the claims made on it ---
    positive events on each side, and the Normal hours that are the
    false-alarm denominator.
    """
    if caption is None:
        caption = (
            "Grouped cross-validation folds. Wells are split twice, "
            "independently: positive wells balanced on events, Normal wells "
            "on hours. Normal hours are the false-alarm denominator; a fold "
            "below roughly 300\\,h cannot resolve a budget of 1 alarm per "
            "100\\,h. Training well counts include the 150 simulated "
            "pseudo-wells, which never enter validation or test."
        )

    lines = [
        "% Auto-generated by: python -m src.data.splits --latex <path>",
        "% Do not edit by hand -- regenerate instead.",
        "\\begin{table}[t]",
        "\\centering",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        "\\begin{tabular}{ccccccc}",
        "\\toprule",
        " & \\multicolumn{2}{c}{Train} & \\multicolumn{2}{c}{Validation}"
        " & \\multicolumn{2}{c}{Test} \\\\",
        "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}",
        "Fold & wells & pos.\\ wells & events & normal h & events & normal h \\\\",
        "\\midrule",
    ]
    for _, r in report.iterrows():
        lines.append(
            f"{int(r['fold'])} & {int(r['n_train_wells'])} & "
            f"{int(r.get('n_train_positive_wells', 0))} & "
            f"{int(r['n_val_positive_events'])} & {r['val_normal_hours']:.1f} & "
            f"{int(r['n_test_positive_events'])} & {r['test_normal_hours']:.1f} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    return "\n".join(lines)
